### ISSUE TITLE
Differentiate Binary type from String one

### ISSUE THREAD

**Issue by lexmag** [lexmag/msgpax#3]
Follows from https://github.com/phoenixframework/phoenix/pull/512#issuecomment-65916072.

I agree that `String.valid?` is expensive operation but it seemed as only option to differentiate Binary type from String one. However, after examining other implementations I tend to pack any binary as String type (e.g. [Ruby](https://github.com/msgpack/msgpack-ruby), [Node.js](https://github.com/msgpack/msgpack-node), [Haskell](https://github.com/msgpack/msgpack-haskell) pack "qwe\xFF" as String).
[Erlang](https://github.com/msgpack/msgpack-erlang) has no problem as it maps charlist (Erlang string) to String type and string (Erlang binary) to Binary type.

@josevalim @awetzel what are your thoughts on this?

**Comment by whatyouhide** [comment]
We now have a `Msgpax.Bin` type as described [in the README](https://github.com/lexmag/msgpax#support-for-the-binary-and-extension-types) and [in the docs for `Msgpax.Bin`](https://hexdocs.pm/msgpax/Msgpax.Bin.html).
