### ISSUE TITLE
Packed struct does not go back to struct.

### ISSUE THREAD

**Issue by andrewrynhard** [lexmag/msgpax#4]
I am trying to send a struct with Msgpax but I can't seem to get the original struct back:
````
iex(1)> contact = %Contact{id: "test", ip: "test"}
%Kademlia.RoutingTable.Contact{id: "test", ip: "test"}
iex(2)> packed = Msgpax.pack! contact
[<<130>>,
 [[[<<162>>, "id"], [<<164>>, "test"]], [[<<162>>, "ip"], [<<164>>, "test"]]]]
iex(3)> unpacked = Msgpax.unpack! packed
%{"id" => "test", "ip" => "test"}
iex(4)> unpacked_struct = struct(Contact, unpacked)
%Kademlia.RoutingTable.Contact{id: nil, ip: nil}
iex(5)> 
````

I suppose this has to do with the following:
````
iex(5)> test = %{:id => "test", :ip => "test"}
%{id: "test", ip: "test"}
iex(6)> unpacked_struct = struct(Contact, test)    
%Kademlia.RoutingTable.Contact{id: "test", ip: "test"}
````
Using atoms instead of strings works. Is this something that can be fixed with Masgpax

**Comment by arynhard** [comment]
I should note that using
````
unpacked = Msgpax.unpack!(packed)
    |> Enum.into(%{}, fn {key, val}
    -> {:erlang.binary_to_atom(key, :utf8), val} end)
````
formats the keys correctly but my question is if this should be done by msgpax itself.

**Comment by lexmag** [comment]
Hey @arynhard, thanks for bringing it in. Currently I'm experimenting with support for struct unpacking, I think it'll be added as `struct: true` option, and with more control over unpacking process with [Ext format addition](https://github.com/lexmag/msgpax/tree/ext-type).

**Comment by arynhard** [comment]
@lexmag Great!

**Comment by whatyouhide** [comment]
Msgpax now provides [`Msgpax.Ext`](https://hexdocs.pm/msgpax/Msgpax.Ext.html) which can be easily used to pack structs; unpacking can be made easier through the use of the [Maptu](https://github.com/whatyouhide/maptu) library. We'll update this issue in case we do any further work around handling structs in Msgpax. :smiley:
