### ISSUE TITLE
Prevent raising Protocol.UndefinedError in Msgpax.pack

### ISSUE THREAD

**Issue by mitchellhenke** [lexmag/msgpax#47]
Hi!

I was curious if it would be possible to explore a way to handle and prevent raising an error when calling `Msgpax.pack/1` on a term that doesn't implement the protocol.

Simple example:

```elixir
iex(1)> Msgpax.pack({})
** (Protocol.UndefinedError) protocol Msgpax.Packer not implemented for {}. This protocol is implemented for: Atom, BitString, DateTime, Float, Integer, List, Map, Msgpax.Bin, Msgpax.Ext, Msgpax.ReservedExt
    (msgpax) deps/msgpax/lib/msgpax/packer.ex:36: Msgpax.Packer.impl_for!/1
    (msgpax) deps/msgpax/lib/msgpax/packer.ex:105: Msgpax.Packer.pack/1
    (msgpax) lib/msgpax.ex:70: Msgpax.pack/2
```

I'm not sure if a similar approach would be appropriate for msgpax, but Jason handles similar issues within a try/catch: https://github.com/michalmuskala/jason/blob/v1.1.2/lib/encode.ex#L34-L40

Thanks for the great library 🙂

**Comment by lexmag** [comment]
Hi, I think it does make sense to adopt non-raising behaviour.
Not sure if it means we need to increase major version though. What do you think?

**Comment by mitchellhenke** [comment]
I think it depends on if you call it a bug or not 🙂 

The docs say

>This function returns `{:ok, iodata}` if the serialization is successful, `{:error, exception}` otherwise

Some people could be depending on the raise behavior and changing that would be a breaking change for them, but I'd see this as a small bug being fixed that doesn't need a major version change.

**Comment by lexmag** [comment]
Please send a pull request. :bowtie:
