### ISSUE TITLE
Array unpacking

### ISSUE THREAD

**Issue by daynyte** [lexmag/msgpax#66]
I'm trying to pack some simple data - a list: [67], which serializes to two bytes: 0x91, 0x43 (dec: 145, 67).

In Python:

```
>>> msgpack.packb([67])
b'\x91C'
>>> list(msgpack.packb([67]))
[145, 67]
>>> msgpack.unpackb(msgpack.packb([67]))
[67]
```

In Elixir:

```
iex(0)> Msgpax.pack([67], iodata: false)
{:ok, <<145, 67>>}
iex(1)> Msgpax.unpack(<<145, 67>>)      
{:ok, ~c"C"}
iex(2)> IO.inspect(~c"C", charlists: :as_lists)
[67]
~c"C"
iex(3)> Msgpax.pack(["C"])
{:ok, [145, [161 | "C"]]}
```

However, I'm expecting Msgpax.unpack(<<145, 67>>) to return [67] instead of a charlist else the input would be ["C"] and the item encoded as a string. I'm still new to Elixir so I may just be missing something.

**Comment by lexmag** [comment]
Hi @dnusr, the existing returned value is correct, as in Elixir `[67]` and `~c"C"` are equivalent data structures, while `"C"` (without `~c`) is another one, binary. More details on charlists and their internal representation is in the link: https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html#charlists.
